name: 'Terraform - plan'

on:
  - push

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: "f90c892c-5122-4368-8629-24033e147e35"
  ARM_TENANT_ID: "e9e9f29c-1e90-4c4f-99d9-43d6e2806804"


permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs: 
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    steps:
    - uses: actions/checkout@v2.0.0
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.3
        terraform_wrapper: false
  
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }} 
        tenant-id: "e9e9f29c-1e90-4c4f-99d9-43d6e2806804"
        subscription-id: "f90c892c-5122-4368-8629-24033e147e35"
        enable-AzPSSession: true 

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: terraform
      shell: bash
    
    - run : echo "arm is $ARM_CLIENT_SECRET"
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -refresh=false  -no-color -out out.plan
      working-directory: terraform
      shell: bash
    
    - name: Terraform Show
      id: show
      run: terraform show -no-color tf.plan 2>&1 > /tmp/plan.txt
      working-directory: terraform
      shell: bash

    - name: Comment PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: 25
        body: ${{steps.plan.outputs.stdout}}


